### PR TITLE
Rename set_logger_raw to try_set_logger_raw

### LINKED ISSUE #204: Rename set_logger_raw to try_set_logger_raw
With respect to the changes made in #187, it makes sense to change set_logger_raw to panic on error (just like set_logger); where set_logger_raw panics on error and try_set_logger_raw returns error.

@alexcrichton @dtolnay

### PR DESCRIPTION
**Pull request by alisha17**
Fixes #204

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me, thanks!

@sfackler do you agree with the rename here?

**Comment by sfackler** [comment]
Seems reasonable to me, but it needs a rebase.

**Comment by alisha17** [comment]
Rebased @sfackler

**Comment by KodrAus** [comment]
Is this good to merge now?

**Comment by sfackler** [comment]
Yep!

**Pull request merged**
