### PR TITLE
Add an error type to FromStr impls

### LINKED ISSUE #119: FromStr impls for LogLevel, LogLevelFilter use () as error type
These implementations should use a dedicated opaque error type rather than `()`, and this error should implement the `Error` trait.

### PR DESCRIPTION
**Pull request by nivkner**
Fixes #119

### CODE REVIEW

**Comment by alexcrichton** [comment]
Awesome, thanks @nivkner! I think in light of https://github.com/rust-lang-nursery/log/issues/142 though we may wish to remove the `Log` prefix here perhaps?

@sfackler do you have thoughts on how to manage breaking changes like this? Do you think we should hold off on merging or maybe merge to a separate branch?

**Comment by dtolnay** [comment]
I would merge to master along with a note in Cargo.toml.

```toml
publish = false # this branch contains breaking changes
```

**Comment by nivkner** [comment]
Removed the `Log` prefix as requested.

**Comment by alexcrichton** [comment]
Thanks @nivkner! We'll take it from here and figure out the best way to land this with other breaking changes to the `log` crate.

**Comment by sfackler** [comment]
Seems fine to merge to master - we can always cut an 0.3.x branch if we need more releases from that version.

**Comment by dtolnay** [comment]
@nivkner any reason these messages are slightly different? I would prefer to pick one or the other.

**Comment by dtolnay** [comment]
Ah, this matches all of the existing error messages. I filed #166 to follow up.

**Pull request merged**
