### PR TITLE
env_logger: Add customized init functions

### PR DESCRIPTION
**Pull request by diwic**
This adds the possibility to customize how to init env_logger by
parsing a custom environment variable, or a logging spec directly.

If you were ever annoyed that `RUST_LOG=debug cargo run` outputted tons of debug info from cargo when all you wanted was to see debug output from the program you wanted to run, you're going to love this feature.

### CODE REVIEW

**Comment by alexcrichton** [comment]
In the past I've thought that we either want a generic `init` or a custom builder type to build up the configuration for this library (rather than a few assorted entrypoint functions), e.g. along the lines of https://github.com/rust-lang-nursery/log/pull/48 (which seems to have fallen by the wayside)

You can filter out logging via `RUST_LOG=foo=debug` where `foo` is the name of the program you're debugging.

**Comment by diwic** [comment]
I don't think there would be any harm in doing both - have a few convenience entry points for the most common usages, and a configuration/builder/etc for more uncommon use cases.

That said, it looks like #48 would be good enough for my use case too, if it actually gets in.

**Comment by alexcrichton** [comment]
Using a builder is generally much more composable as it's easier to add new functions and it's "one less concept to understand" because there's one main entry point (`init`) and then maximal customization through a builder. The builder can have convenience functions for parsing specs or looking at different environment variables.

**Comment by dbrgn** [comment]
Yes, configuration options would be very nice.

**Comment by dtolnay** [comment]
This is now supported using the builder from #48. To expand on what Alex mentioned about composability: in #146 we are considering distinguishing between `init` which panics and `try_init` which returns a Result. This PR would have required us to consider also `try_init_with_env_var` and `try_init_with_spec` which is an example of not being nicely composable.

**Pull request closed without merging**
