### PR TITLE
Updated Regex dependency

### PR DESCRIPTION
**Pull request by Aaronepower**

### CODE REVIEW

**Comment by sfackler** [comment]
Will this bump env-logger's minimum version? I'm not sure if we actually keep track of what is is right now.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Pedantically speaking there were [breaking changes](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#020) to the syntax of regexes, so yes this'd require bumping versions. Practically speaking I wouldn't bump it.

**Comment by sfackler** [comment]
I'm more worried about jumping to a minimum rustc version of 1.12 than the regex syntax change.

**Comment by alexcrichton** [comment]
True yeah. @Aaronepower could you elaborate on the motivation for this PR? It's typically hard to do so given empty PR descriptions...

**Comment by Aaronepower** [comment]
@alexcrichton Yes, you currently cannot use env_logger/log with regex `0.2`. Also as far as I remember official rust crates supports two rustc versions back so I didn't think this would be a problem.

**Comment by sfackler** [comment]
Why can't you? Cargo should behave just fine with two versions of regex.

**Comment by Aaronepower** [comment]
@sfackler Here is the error I get trying to use regex `0.2` with current env_logger in tokei, and my dependency tree.

```
error: failed to select a version for `thread_local` (required by `regex`):
all possible versions conflict with previously selected versions of `thread_local`
  version 0.2.7 in use by thread_local v0.2.7
  version 0.3.0 in use by thread_local v0.3.0
  possible versions to select: 0.3.2
```

```
tokei v5.0.5 (file:///Users/aep/src/tokei)
├── clap v2.19.1
│   ├── ansi_term v0.9.0
│   ├── bitflags v0.7.0
│   ├── libc v0.2.18
│   ├── strsim v0.5.2
│   ├── term_size v0.2.1
│   │   └── libc v0.2.18 (*)
│   ├── unicode-segmentation v0.1.3
│   ├── unicode-width v0.1.3
│   ├── vec_map v0.6.0
│   └── yaml-rust v0.3.5
├── encoding v0.2.33
│   ├── encoding-index-japanese v1.20141219.5
│   │   └── encoding_index_tests v0.1.4
│   ├── encoding-index-korean v1.20141219.5
│   │   └── encoding_index_tests v0.1.4 (*)
│   ├── encoding-index-simpchinese v1.20141219.5
│   │   └── encoding_index_tests v0.1.4 (*)
│   ├── encoding-index-singlebyte v1.20141219.5
│   │   └── encoding_index_tests v0.1.4 (*)
│   └── encoding-index-tradchinese v1.20141219.5
│       └── encoding_index_tests v0.1.4 (*)
├── env_logger v0.3.5
│   ├── log v0.3.6
│   └── regex v0.1.80
│       ├── aho-corasick v0.5.3
│       │   └── memchr v0.1.11
│       │       └── libc v0.2.18 (*)
│       ├── memchr v0.1.11 (*)
│       ├── regex-syntax v0.3.9
│       ├── thread_local v0.2.7
│       │   └── thread-id v2.0.0
│       │       ├── kernel32-sys v0.2.2
│       │       │   └── winapi v0.2.8
│       │       └── libc v0.2.18 (*)
│       └── utf8-ranges v0.1.3
├── errln v0.1.0
├── ignore v0.1.6
│   ├── crossbeam v0.2.10
│   ├── globset v0.1.2
│   │   ├── aho-corasick v0.5.3 (*)
│   │   ├── fnv v1.0.5
│   │   ├── lazy_static v0.2.2
│   │   ├── log v0.3.6 (*)
│   │   ├── memchr v0.1.11 (*)
│   │   └── regex v0.1.80 (*)
│   ├── lazy_static v0.2.2 (*)
│   ├── log v0.3.6 (*)
│   ├── memchr v0.1.11 (*)
│   ├── regex v0.1.80 (*)
│   ├── thread_local v0.3.0
│   │   ├── thread-id v3.0.0
│   │   │   └── libc v0.2.18 (*)
│   │   └── unreachable v0.1.1
│   │       └── void v1.0.2
│   └── walkdir v1.0.3
├── lazy_static v0.2.2 (*)
├── log v0.3.6 (*)
├── maplit v0.1.4
├── rayon v0.6.0
│   ├── deque v0.3.1
│   │   └── rand v0.3.15
│   │       └── libc v0.2.18 (*)
│   ├── libc v0.2.18 (*)
│   ├── num_cpus v1.2.0
│   │   └── libc v0.2.18 (*)
│   └── rand v0.3.15 (*)
├── regex v0.1.80 (*)
├── serde v0.8.19
└── serde_json v0.8.4
    ├── dtoa v0.2.2
    ├── itoa v0.1.1
    ├── num-traits v0.1.36
    └── serde v0.8.19 (*)
```

**Comment by sfackler** [comment]
What happens if you `cargo update`? I've seen cargo get wedged like that before and that has helped get it working again.

**Comment by Aaronepower** [comment]
@sfackler Ah that did fix it, feel free to close, or wait till there is a major version bump.

**Comment by upsuper** [comment]
Ping on this.

We want to upgrade the regex dependency of Servo to 0.2, and env_logger is the only remaining crate that haven't upgraded yet. @sfackler [commented](https://github.com/rust-lang-nursery/log/pull/100#issuecomment-271997685) in #100 several days ago that we can land this and cut a 0.4 release.

**Comment by sfackler** [comment]
Yep, sorry!

**Comment by sfackler** [comment]
Released 0.4.0

**Comment by upsuper** [comment]
Thanks!

**Pull request merged**
